# Generated by Django 5.1.3 on 2024-12-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="complete",
            new_name="completed",
        ),
    ]
